-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            contrast = 1.0,
            noise = 0.0,
            vibrancy = 0.0,
        },
        rounding = 12,
    },
    general = {
        col = {
            active_border = "0xff1a5fb4",
        },
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1200@60.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.exec_cmd("alacritty"))
hl.unbind("SUPER + X")
hl.bind("SUPER + X", hl.dsp.window.close())
hl.unbind("SUPER + Tab")
hl.bind("SUPER + Tab", hl.dsp.focus({ workspace = "+1" }))
hl.unbind("SUPER + SHIFT + Tab")
hl.bind("SUPER + SHIFT + Tab", hl.dsp.focus({ workspace = -1 }))
hl.unbind("SUPER + SHIFT + Z")
hl.bind("SUPER + SHIFT + Z", hl.dsp.workspace.toggle_special(""))
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("dolphin"))
hl.unbind("SUPER + CTRL + ESCAPE")
hl.bind("SUPER + CTRL + ESCAPE", hl.dsp.exit())
hl.unbind("SUPER + backslash")
hl.bind("SUPER + backslash", hl.dsp.window.float({ action = "toggle" }))
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.window.fullscreen())
hl.unbind("SUPER + mouse:272")
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), {
    mouse = true,
})
hl.unbind("SUPER + mouse:273")
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), {
    mouse = true,
})
hl.unbind("XF86AudioRaiseVolume")
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), {
    repeating = true,
})
hl.unbind("XF86AudioLowerVolume")
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), {
    repeating = true,
})
hl.unbind("XF86AudioMute")
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), {
    repeating = true,
})
hl.unbind("XF86AudioMicMute")
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), {
    repeating = true,
})
hl.unbind("XF86MonBrightnessUp")
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), {
    repeating = true,
})
hl.unbind("XF86MonBrightnessDown")
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), {
    repeating = true,
})
hl.unbind("XF86AudioNext")
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), {
    locked = true,
})
hl.unbind("XF86AudioPause")
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), {
    locked = true,
})
hl.unbind("XF86AudioPlay")
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), {
    locked = true,
})
hl.unbind("XF86AudioPrev")
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), {
    locked = true,
})

-- Layer rules
hl.layer_rule({
    name = "ignore alpha",
    match = {
        namespace = ".*",
    },
    ignore_alpha = 0.0,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/share/libpam-kwallet-common/pam_kwallet_init")
    hl.exec_cmd("busctl --user call org.kde.kwalletd6 /modules/kwalletd6 org.kde.KWallet open sxs kdewallet 0 ''")
end)
