[font]
size = 10.0

# Set the primary font to Monaspace Xenon NF
[font.normal]
family = "Monaspace Xenon NF"
style = "Regular"

[font.bold]
family = "Monaspace Xenon NF"
style = "Bold"

[font.italic]
family = "Monaspace Xenon NF"
style = "Italic"

[font.bold_italic]
family = "Monaspace Xenon NF"
style = "Bold Italic"

# Primary background and foreground colors
[colors.primary]
background = "{{colors.background.dark.hex}}"
foreground = "{{colors.on_background.dark.hex}}"

[colors.cursor]
cursor = "{{colors.tertiary.dark.hex}}"

# Normal color palette (used by terminal applications)
[colors.normal]
black   = "#000000"
red     = "#cc0000"
green   = "#00cc00"
yellow  = "#cccc00"
blue    = "#0000cc"
magenta = "#cc00cc"
cyan    = "#00cccc"
white   = "#cccccc"

# Bright color palette
[colors.bright]
black   = "#333333"
red     = "#ff0000"
green   = "#00ff00"
yellow  = "#ffff00"
blue    = "#0000ff"
magenta = "#ff00ff"
cyan    = "#00ffff"
white   = "#ffffff"

[window]
opacity={{custom.alpha_decimal}}
blur=true

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
  { key = "C",       mods = "Control|Shift", action = "Copy"  },
  { key = "V",       mods = "Control|Shift", action = "Paste" },
  { key = "Enter",   mods = "Shift",         chars = "\n" },
  { key = "Equals",  mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus",   mods = "Control",       action = "DecreaseFontSize" },
  { key = "Key0",    mods = "Control",       action = "ResetFontSize"    },
]
